### ISSUE TITLE
Disponibilidade para outros bancos

### ISSUE THREAD

**Issue by dbcesar** [romuloceccon/finance-quote-brazil#3]
Olá, 

Gostaria de saber se esse módulo é compatível ou indicado para acompanhar Fundos de Investimento e Letras de Câmbio (LCA/LCI).

Caso positivo, com o que tem desenvolvido é possivel pegar dados de alguma dessas instituições?

Easynvest
XP investimentos
Banco Inter

Muito obrigado.

**Comment by romuloceccon** [comment]
@dbcesar, esse módulo não faz nada mais do que baixar uma página (HTML, json, XLSX etc.) usando Perl e retornar os dados solicitados usando o padrão definido pelo [`Finance::Quote`](http://search.cpan.org/~ecocode/Finance-Quote-1.47/lib/Finance/Quote.pm).

Pra conseguir o que você precisa basta que essa página possa ser baixada sem intervenção humana. O tamanho do trabalho vai depender da complexidade do layout.

Obviamente isso tudo assume que exista uma página atualizada periodicamente com as cotações dos fundos que te interessam.

**Comment by dbcesar** [comment]
Obrigado @romuloceccon, vou verificar onde posso encontrar essas informações para as instituições que mencionei.
